using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Quillwright.Templates.Generator;

/// <summary>Emits the binder source for one template model.</summary>
internal static class TemplateBinderWriter
{
    private const string Culture = "global::System.Globalization.CultureInfo.CurrentCulture";

    public static string Write(TemplateModelInfo model)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        if (model.Namespace.Length > 0)
            source.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();

        source.Append("partial ").Append(model.TypeKeyword).Append(' ').Append(model.TypeName)
            .AppendLine(" : global::Quillwright.Templates.ITemplateModel");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Reads the members of this model by template name, without reflection.</summary>");
        source.Append("    public static global::Quillwright.Templates.ITemplateBinder TemplateBinder => ")
            .Append(model.BinderName).AppendLine(".Instance;");
        source.AppendLine("}");
        source.AppendLine();

        WriteBinder(source, model);
        return source.ToString();
    }

    private static void WriteBinder(StringBuilder source, TemplateModelInfo model)
    {
        source.Append("file sealed class ").Append(model.BinderName)
            .AppendLine(" : global::Quillwright.Templates.ITemplateBinder");
        source.AppendLine("{");
        source.Append("    public static readonly ").Append(model.BinderName).Append(" Instance = new ")
            .Append(model.BinderName).AppendLine("();");
        source.AppendLine();

        source.Append("    private static readonly string[] _names = [")
            .Append(string.Join(", ", model.Members.Select(static m => Quote(m.Name))))
            .AppendLine("];");
        source.AppendLine();
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<string> Names => _names;");
        source.AppendLine();

        WriteLookup(
            source, model, MemberRole.Text,
            "public bool TryGetText(object model, string name, out string? value)",
            "value", "null",
            static member => "value = " + TextExpression(member) + ";");

        WriteLookup(
            source, model, MemberRole.Rows,
            "public bool TryGetRows(object model, string name, out global::Quillwright.Templates.TemplateRows rows)",
            "rows", "default",
            static member => "rows = " + RowsExpression(member) + ";");

        WriteLookup(
            source, model, MemberRole.Condition,
            "public bool TryGetCondition(object model, string name, out bool value)",
            "value", "false",
            static member => "value = typed." + member.Accessor + ";");

        WriteLookup(
            source, model, MemberRole.Image,
            "public bool TryGetImage(object model, string name, out global::Quillwright.Templates.TemplateImage image)",
            "image", "default",
            static member => "if (typed." + member.Accessor + " is null) break;" +
                             "\n                image = " + ImageExpression(member) + ";");

        source.AppendLine("}");
    }

    private static void WriteLookup(
        StringBuilder source,
        TemplateModelInfo model,
        MemberRole role,
        string signature,
        string outName,
        string missing,
        System.Func<TemplateMember, string> body)
    {
        List<TemplateMember> members = [.. model.Members.Where(member => member.Role == role)];

        source.Append("    ").AppendLine(signature);
        source.AppendLine("    {");
        if (members.Count == 0)
        {
            source.Append("        ").Append(outName).Append(" = ").Append(missing).AppendLine(";");
            source.AppendLine("        return false;");
            source.AppendLine("    }");
            source.AppendLine();
            return;
        }

        source.Append("        var typed = (").Append(model.FullTypeName).AppendLine(")model;");
        source.AppendLine("        switch (name)");
        source.AppendLine("        {");
        foreach (TemplateMember member in members)
        {
            source.Append("            case ").Append(Quote(member.Name)).AppendLine(":");
            source.Append("                ").AppendLine(body(member));
            source.AppendLine("                return true;");
        }

        source.AppendLine("        }");
        source.AppendLine();
        source.Append("        ").Append(outName).Append(" = ").Append(missing).AppendLine(";");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static string TextExpression(TemplateMember member)
    {
        string access = "typed." + member.Accessor;
        if (member.Format is { } format)
            return $"({access} as global::System.IFormattable)?.ToString({Quote(format)}, {Culture})";

        // A non-nullable value type never needs the null-conditional, and the compiler
        // rejects it there, so the two cases are spelled out rather than guessed.
        return member.IsNullable ? access + "?.ToString()" : access + ".ToString()";
    }

    private static string RowsExpression(TemplateMember member) =>
        "new global::Quillwright.Templates.TemplateRows(" +
        "global::System.Linq.Enumerable.ToArray(global::System.Linq.Enumerable.Cast<object>(" +
        "(global::System.Collections.IEnumerable?)typed." + member.Accessor +
        " ?? global::System.Array.Empty<object>())), " + member.RowBinderType + ")";

    private static string ImageExpression(TemplateMember member) =>
        "new global::Quillwright.Templates.TemplateImage(typed." + member.Accessor + ", " +
        LengthExpression(member.WidthCentimeters) + ", " + LengthExpression(member.HeightCentimeters) + ")";

    private static string LengthExpression(double centimeters) =>
        centimeters <= 0
            ? "null"
            : "global::Quillwright.Primitives.Length.FromCentimeters(" +
              centimeters.ToString("R", CultureInfo.InvariantCulture) + ")";

    private static string Quote(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
